### ISSUE TITLE
Array to String error when filtering by reference type and navigating to next page

### ISSUE THREAD

**Issue by planeth44** [philiplb/CRUDlex#100]
Let's say I have a table `produit` and one field in the table is a reference to another table `client`.

On the productList page, I filter by the client_id field.
The result gives me 2 pages.
If I navigate to the page 2, the error occurs.

This the  DBALException message:
```
An exception occurred while executing 'SELECT COUNT(id) FROM `produit` `produit` WHERE (`id_client` = ?) AND (deleted_at IS NULL)' with params [{"id":<UUID>"}]:

Notice: Array to string conversion
```

The URL of the page:
`crud/produit?crudPage=1&crudSortField=created_at&crudSortAscending=true&crudFilterid_client%5Bid%5D=<UUID>`

**Comment by philiplb** [comment]
Ou, good find. Thx for the report!

**Comment by planeth44** [comment]
I came up with a temporary fix in the list template
```
            {% if crudData.getDefinition().getType(filterField) == 'reference' and filterValue.id is defined %}
                {% set filterValue = filterValue.id %}
            {% endif %}
```

**Comment by philiplb** [comment]
This has been fixed via https://github.com/philiplb/CRUDlex/commit/8a1a6eb3e2134c93554edba2765531c495835970 .
Looking forward to the release of 0.14.0 tomorrow or monday. :)

**Comment by planeth44** [comment]
Splendid!
