### ISSUE TITLE
M:N relationships

### ISSUE THREAD

**Issue by philiplb** [philiplb/CRUDlex#20]
- [x] basic implementation
  - [x] design YML fields and extend the EntityDefinition with them
  - [x] render
  - [x] create, UI having a basic implementation with a multiselect
  - [x] update: same as on creation, but delete existing relationship entries upfront
- [x] [Fri Sep 09 22:25:51.330299 2016] [:error] [pid 2714] [client ::1:50576] PHP Notice:  Undefined index: isOpenOnSundays in /Users/philiplb/Sites/CRUDlex/src/CRUDlex/AbstractData.php on line 79, referer: http://localhost/~philiplb/CRUDlexSample/web/crud/library/create
- [x] [Sat Sep 10 08:39:11.836594 2016] [:error] [pid 26079] [client ::1:52711] PHP Warning:  Invalid argument supplied for foreach() in /Users/philiplb/Sites/CRUDlex/src/CRUDlex/MySQLData.php on line 318, referer: http://localhost/~philiplb/CRUDlexSample/web/crud/library/create
- [x] adding a validator
- [x] extended UI with one of
  - http://selectize.github.io/selectize.js/
  - https://harvesthq.github.io/chosen/
  - https://select2.github.io
- [x] care about constraints
  - [x] required
  - [x] unique
- [x] don't allow to sort by a many field on the list view, to be mentioned in the docs
- [x] filter
- [x] unit tests
- [x] docs
  - [x] write missing API docs
  - [x] data type with sample
  - [x] mention the missing sorting option
  - [x] regenerate docs

**Comment by acidline** [comment]
Hi,

Are you working on this feature ? I think it's really helpful if select options on reference field can have multiple attributes.

Thank's with anticipation

**Comment by philiplb** [comment]
Hi @acidline,
currently not yet, but one of the very next things to work on actually. :)

**Comment by acidline** [comment]
Very good news !
What is your choices to implements this feature ? Do you need some help ?

**Comment by philiplb** [comment]
@acidline 
Thx for the offer. :) Planing is some Ajax driven selection and building up the referenced items to save. each of the selected ones with a little [x] to remove them again.
Needing some help: Actually not I think, this stuff shouldn't be super big as soon as I find some time to start with it. :)
