### ISSUE TITLE
fatal error due to changed arguments

### ISSUE THREAD

**Issue by Achati** [philiplb/CRUDlex#29]
api: listEntries( array $filter = array(), integer $skip = null, integer $amount = null )
called with: array, null, 1
to get only the first result

Catchable fatal error: Argument 2 passed to CRUDlex\CRUDMySQLData::listEntries() must be of the type array, integer given, called in ...\index.php on line 293 and defined in ...\app\vendor\philiplb\crudlex\src\CRUDlex\CRUDMySQLData.php on line 107

**Comment by philiplb** [comment]
Signature changed in the current master version and the docs for 0.9.6 don't apply anymore.
