### ISSUE TITLE
Feature Request: Random String as database id

### ISSUE THREAD

**Issue by timfreiheit** [philiplb/CRUDlex#36]
it would be useful to have the possibility to replace the auto incremented id with an random string.
My current solution is to add an unique objectId field.

**Comment by philiplb** [comment]
@timfreiheit 
What is your specific use case?

**Comment by timfreiheit** [comment]
I have an api which modify an existing entry. But with an auto incremented id it is easy to guess the other existing ids. At this point there is no other validation with an session token possible. It is like the data model in parse. If you know the id you have the right to modify it.

**Comment by philiplb** [comment]
Can be easily added but you should think of a different solution than security by obscurity. The goto solution would be http://silex.sensiolabs.org/doc/providers/security.html and maybe add https://github.com/philiplb/CRUDlexUser .

**Comment by philiplb** [comment]
Implemented in 0ab7cd0f14adbf699f8a0537cbed8e30181121ef
