### ISSUE TITLE
0.9.9 broken with silex/web-profiler ^1.0

### ISSUE THREAD

**Issue by ashorlivs** [philiplb/CRUDlex#41]
First of all your congratulations for putting up CRUDlex!

[CRUDlexSample](https://github.com/philiplb/CRUDlexSample) deploys v.0.9.7 of ou the box.
Adding [Web Profiler](https://github.com/silexphp/Silex-WebProfiler) works well also:
```
    "require": {
        "philiplb/crudlex": "0.9.7",
        "silex/web-profiler": "^1.0"
    }
```

Unfortunately upgrading to v0.9.9 conflicts with the Web Profiler: 
```
Twig_Error_Syntax in ExpressionParser.php line 604:
Unknown "trans" filter in "@crud/list.twig" at line 22.
```

Downgrade to v0.9.8:
```
Twig_Error_Syntax in ExpressionParser.php line 604:
Unknown "trans" filter in "@crud/list.twig" at line 14.
```

Removing silex/web-profiler (v1.0.8) restores CRUDlex v0.9.8 - v0.9.9

Any hints?

**Comment by philiplb** [comment]
Will investigate and update the sample project.

**Comment by philiplb** [comment]
For now, I updated the sample project. It contains now tags for 0.9.7, 0.9.8, 0.9.9 and 0.9.x-dev (master):
https://github.com/philiplb/CRUDlexSample/releases

**Comment by ashorlivs** [comment]
Cool, but breaks compatibility with CRUDlexUser 
```
ContextErrorException in CRUDUserSetup.php line 57:
Catchable Fatal Error: Argument 1 passed to CRUDlex\CRUDUserSetup::addEvents() must be an instance of CRUDlex\CRUDData, instance of CRUDlex\MySQLData given
```

**Comment by philiplb** [comment]
That's true. All dependend projects will get their tags and updates.

**Comment by philiplb** [comment]
Made it work by registering the in advance TranslationServiceProvider:

```php
$app->register(new \Silex\Provider\TranslationServiceProvider(), array(
    'locale_fallbacks' => array('en'),
));
```

See this now added hint: http://philiplb.github.io/CRUDlex/docs/html/0.9.10/manual/extendedfeatures.html#combine-with-the-web-profiler

**Comment by ashorlivs** [comment]
:+1: 

This project gets more exciting each day!

**Comment by philiplb** [comment]
Glad you like it. :-)

**Comment by philiplb** [comment]
@ashorlivs Updated CRUDlexUser to the versioning scheme

**Comment by ashorlivs** [comment]
Can't test in my project at the moment because I'm on the stable version, but seems OK @ dev.
