### ISSUE TITLE
Improvement request: use proper Twig truncate() filter inside templates

### ISSUE THREAD

**Issue by ashorlivs** [philiplb/CRUDlex#42]
E.g.: 
```
{{ basename|truncate(30) }}
```
outputs the 30 first characters and adds '...' (default separator) only if the string is longer than that.

More relevant than the hard-coded:
```
{{ basename|slice(0, 30) }}...
```

I'll do it myself as soon as I finish my current project (~2 weeks) and read carefully how to contribute an existing project.

**Comment by philiplb** [comment]
Good find, thank you. Didn't know about the truncate-filter. But I rather not include it to not have another dependency to "twig/extensions" for a minor convinience.

**Comment by ashorlivs** [comment]
As you wish!
