### ISSUE TITLE
pushEvent after create + file upload

### ISSUE THREAD

**Issue by Germain-Italic** [philiplb/CRUDlex#44]
Hi,
when working with `pushEvents` I am trying to process a file automatically after upload.

I'm using an `after create` event, but it seems that it is fired **before** the file is actually uploaded (not present on the disk).

The following code sample always returns `$file = false`:

```
$xls2json = function(CRUDlex\CRUDEntity $entity) {

    $filename   = $entity->get('filename');

    $fileid     = $entity->get('id');
    $path       = dirname(__DIR__).'/www/uploads/imports'; // any way to get it from the .yml?
    $filepath   = $path.'/'.$fileid.'/'.$filename;

    $file       = file_exists($filepath) ? $filepath : false;

    var_dump($file);
    exit();
    return true;
};
$app['crud']->getData('imports')->pushEvent('after', 'create', $xls2json);
```

**Comment by ashorlivs** [comment]
Not sure why it's closed. Is it normal that the file is being uploaded *after* the `after create` event?

**Comment by philiplb** [comment]
This is due to the nature of this current after-events being triggered as soon as the object is saved to the database. Afterwards, the files are handled.
I might just introduce a set of new before/after-events for files.

**Comment by Germain-Italic** [comment]
Got it working! Thanks :+1:
