### ISSUE TITLE
pushEvents + database access

### ISSUE THREAD

**Issue by ashorlivs** [philiplb/CRUDlex#45]
This is somehow related to Issue #44.

I would also like to fill a field in the database from inside a pushEvents.

I have made some tests in a separate controller and succeeded to access the database by invoking `$data = $app['crud']->getData($entity);` and then using CRUDlex's setters.

However when trying to do it from inside my pushEvents function, I can't access the $app object. Is there any recommended way to to use the API's functions inside a pushEvents callback?

Sample code tryings and error:

```
$xls2json = function(CRUDlex\CRUDEntity $entity) {
    global $app;
    $data = $app['crud']->getData($entity);
...
$app['crud']->getData('imports')->pushEvent('after', 'create', $xls2json);
```

or

```
$xls2json = function(CRUDlex\CRUDEntity $entity) use ($app) {
    $data = $app['crud']->getData($entity);
...
$app['crud']->getData('imports')->pushEvent('after', 'create', $xls2json);
```

both lead to:

```
ContextErrorException in CRUDServiceProvider.php line 289:
Warning: array_key_exists(): The first argument should be either a string or an integer
```

**Comment by philiplb** [comment]
The later should work, maybe the error is somewhere else.
What you also could try:
```php
$data = $app['crud']->getData($entity);
$xls2json = function(CRUDlex\CRUDEntity $entity) use ($data) {
    ...
...
$app['crud']->getData('imports')->pushEvent('after', 'create', $xls2json);
```

**Comment by ashorlivs** [comment]
Just tried. This works:
```
$data = $app['crud'];
$xls2json = function(CRUDlex\CRUDEntity $entity) use ($data) {
    $import     = $data->getData('imports');
```

But I can't get the entity name (`$entity-> definition->table`) and ID (`$entity-> entity->id`) because they are private.

I can do it by creating a class that `extends CRUDEntity` but it seems a bit disproportionate.

**Comment by philiplb** [comment]
For the definition:
```php
$definition = $entity->getDefinition();
```

For the id:
```php
$id = $entity->get('id');
```

For the table:
```php
$table = $definition->getTable();
```

**Comment by ashorlivs** [comment]
Awesome!
