### ISSUE TITLE
Wrong class in form.twig ("crudFormDelete" instead of "crudFormEdit")

### ISSUE THREAD

**Issue by j-koenig** [philiplb/CRUDlex#46]
https://github.com/philiplb/CRUDlex/blob/7dc9088725472fabafc7c72069ef045960b03b28/src/views/form.twig#L21

**Comment by philiplb** [comment]
Fixed in fbe2c119d15db40f792cc5ee21da36e1050b293f

**Comment by j-koenig** [comment]
Das ging flott :D


Philip <notifications@github.com> schrieb am Di., 22. März 2016 10:49:
