### ISSUE TITLE
Missing API doc: using CRUDlex in custom controllers

### ISSUE THREAD

**Issue by Germain-Italic** [philiplb/CRUDlex#47]
Hi,
My CRUDlex app is setup, and I would like to be able to read/write outside CRUDlex (in my custom controllers).

I can't understand how to use the API for that.
I can retrieve the definition: `$app['crud']->getData('player')->getDefinition();`
The MYSQLdata object: `$app['crud']->getData('player')`

But I can't figure out how to initiate an Entity so that I can perform `->set` and `->create` operations.

Any tips about that would be appreciated!

**Comment by Germain-Italic** [comment]
I finally got it working (well it took me literally all day, but that's how one learns).
Does the code below looks correct to you?

```
// controllers.php
// (...)
$app->get('/test', function () use ($app) {

	$row = array(
		"email"       => "test@test.test",
		"first_name"  => "first",
		"last_name"   => "last",
		"hometown"    => "home",
		"gender"      => "male",
		"locale"      => "fr",
		"is_verified" => 0
	);


	$player     = $app['crud']->getData('player');
	$definition = $player->getDefinition();
	$entity     = $player->createEmpty();
	$fields     = $definition->getFieldNames();

	foreach ($fields as $field )
		if (array_key_exists($field, $row))
			$entity->set($field, $row[$field]);

	if ($player->create($entity))
		exit("inserted with id ".$entity->get('id'));
});
// (...)
```

**Comment by philiplb** [comment]
Hi,
your syntax is correct. Wheras I would not recommend this minimal ORM with weaknesses over something like Doctrine2. Its functionality is quite minimal. But if it does, what you need, go for it. :)
