### ISSUE TITLE
Add more flexibility to template

### ISSUE THREAD

**Issue by acidline** [philiplb/CRUDlex#48]
Hi @philiplb,

I'm trying your projet in professionnal context. What do you think to enhance templating with these functionalities : 

- Provide a **tab system** directly in crud yaml definition
- Provide the possibility to **add some extra css class directly** in crud yaml definition
- A very functional feature : **duplicate fields or duplicate group field**
- Add the possibility to **embed form in form**. Ex : A person profile as a part experience. It's helpful to add experience form directly in the "base" form (and add the possibility to add more one experience)

For me, overriding every template is a bad idea ...

A better solution is the possibility to override easily the EntityDefinition class.

Actually, if I want to override the EntityDefinition to add some extra functionalities, I need to extends the CRUDlex Service Provider, MySQLDataFactory and his interface etc... because there is an object type hinting in methods of class.

A very good exemple to illustrate my purposes, is the Django Admin from Python World and his module Django Suit http://djangosuit.com/

What do you think about these functionality ? There is no equivalent to Symfony/Silex community in front of Django community

**Comment by philiplb** [comment]
Hi,
sry for the long delay in the answer. Thank you for your feedback.
Let's go point by point through it. :)

- Provide a **tab system** directly in crud yaml definition
-> This would mix up the data definition and layout, won't happen. but a second configuration file would be possible. Can you elaborate more what this should be despite of overriding the layout.twig?

- Provide the possibility to **add some extra css class directly** in crud yaml definition
-> See above, why not. Current way: Just override the header.twig.

- A very functional feature : **duplicate fields or duplicate group field**
-> So the unique-constraint spread above multiple fields? If yes, more constraints will come somewhat soon. Currently, I'm separating the validation part into an own library which will make this possible: https://github.com/philiplb/Valdi

- Add the possibility to **embed form in form**. Ex : A person profile as a part experience. It's helpful to add experience form directly in the "base" form (and add the possibility to add more one experience)
-> Adding children to a parent entity (be it 1:n or m:n) directly within the form? This is planned and often requested here.

Can you elaborate more why you think overriding templates? The actual use case would be good. Offering some config files feels limiting as the use case is different for every project and user.

And what functionality do you want to put inside the EntityDefinition? There should be a better solution. Maybe offering a overridable factory where you can return your own, inherited EntityDefinition.

**Comment by philiplb** [comment]
Extracted features:
https://github.com/philiplb/CRUDlex/issues/52
https://github.com/philiplb/CRUDlex/issues/53

Feel free to reopen to further discuss the other points.
