### ISSUE TITLE
i want exteds library code

### ISSUE THREAD

**Issue by ErkinAkbudak** [philiplb/CRUDlex#54]
hi, i want change my post values before saving. For example. user post "3.14" i want just "3"
`explode('.', $_GET['blabla']);`

my other question.i use image data type. it is work. but it not showing as image. it showing as text.
i want see image on list table.

my english is bad, sorry.

**Comment by philiplb** [comment]
Hi,
have a look at the before create and before save events here: http://philiplb.github.io/CRUDlex/docs/html/0.9.10/manual/events.html

For the other question: There is no image type available so far. But you can upload/handle any binary files via the file type: http://philiplb.github.io/CRUDlex/docs/html/0.9.10/manual/datatypes.html#file
