### ISSUE TITLE
Unhelpful error message: "Template "@crud/Field.twig" is not defined"

### ISSUE THREAD

**Issue by jmfayard** [philiplb/CRUDlex#58]
Hello, would be great to have clearer error messages when we type a sql attribute name.

Let say we have a table called `export` with a column `user_id`

If you do this kind of type, 

```diff
export:
  fields:
-    user_id:
+    user:
```

... the error is not perfect, but you can understand what is going on

![image](https://cloud.githubusercontent.com/assets/459464/17432914/14a91a1a-5b02-11e6-9bfe-63c7bf9e43da.png)

On the other hand if you do something like this

```diff
-  filter: [user_id]
+  filter: [user]

-  listFields: [user_id]
+  listFields: [user]
```

then you wonder what causes

![image](https://cloud.githubusercontent.com/assets/459464/17432941/30bf7c8a-5b02-11e6-9d3f-548cd29ba389.png)

**Comment by philiplb** [comment]
<img width="981" alt="screen shot 2016-08-20 at 01 23 57" src="https://cloud.githubusercontent.com/assets/1672238/17826813/ce5130ec-6674-11e6-9355-42c4939a63aa.png">

Fixed in https://github.com/philiplb/CRUDlex/commit/043e1807ad639c886c283394cffdaace1c2ddece
