### ISSUE TITLE
Question: PDO vs Doctrine?

### ISSUE THREAD

**Issue by marcelloh** [philiplb/CRUDlex#78]
CRUDlex now is coupled with Doctrine.
Could it be decoupled, so poeple can use a database solution of their choice?
Like the standard PDO for example?

**Comment by philiplb** [comment]
Hi,
sure, you could just write an implementation of the AbstractData class using pure PDO: http://philiplb.github.io/CRUDlex/docs/html/0.11.0/api/AbstractData.html

Feel free to reopen if you have any question left. :)
