### ISSUE TITLE
Question: Filtering?

### ISSUE THREAD

**Issue by marcelloh** [philiplb/CRUDlex#80]
Now it's possible to filter on predefined fields.
Could it be possible that there are fielders per field, like on top of 'Name' you have a filter that only search into the name-column, and on top of 'Age' you have a filter that will only look into the age-column?

**Comment by philiplb** [comment]
I think this is already possible with the filter feature? http://philiplb.github.io/CRUDlex/docs/html/0.11.0/manual/extendedfeatures.html#filters

Feel free to reopen the issue if you have any more questions or feedback. :)
