### ISSUE TITLE
Question: Override configuration

### ISSUE THREAD

**Issue by marcelloh** [philiplb/CRUDlex#81]
Would it be possible to override certain configurations in realtime,
so I can have a list per user.

We have this:
listFields: [id, created_at, updated_at, author, title]
and it's the same for all users.

When I can override this, because a user is capable of having a personalized view,
I could store it somewhere [author, title, id, created_at, updated_at]
and restore it just before I show the list.

Or even make some fields hidden for this user:
listFields: [id, author, title]

And some would like me to have a personalized pagesize as well.

**Comment by philiplb** [comment]
So user A gets a different listFields configuration than user B?
As CRUDlex is itself is not tied to any security component, this is not currently possible. But what you could do is: Extend the ControllerProvider class and override the function showList.
There, you could:
- check whether the current entity is the one to modify
- grab the definition from $app['crud']->get('yourEntity')->getDefinition()
- set the listFields to show: https://github.com/philiplb/CRUDlex/blob/master/src/CRUDlex/EntityDefinition.php#L202
- call parent::showList()

Feel free to reopen the issue if you have any more questions or feedback. :)

**Comment by marcelloh** [comment]
Yes; User A gets a different view.

Nice idea, perhaps with the stuff you giving me, I'm going to try some of it :-)
