### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by jmfayard** [philiplb/CRUDlex#84]
Hello, in my company I implemented an ad-hoc "Batch operations" feature, and I'm thinking about backporting it to crudlex

In my case we wanted to delete all selected entries, but that could be extended for example to have a CSV export

![image](https://cloud.githubusercontent.com/assets/459464/24715555/0eb7b294-1a2c-11e7-86f2-d8f4a666d920.png)

What could be a good api for this?

first draft in pseudo-code

```
$app['crud']->addBatchOperation(new MyCrudlexBatchOperation())
class MyCrudlexBatchOperation extends BatchOperation
   fun support(EntityDefinition definition) => true or false
   fun label => "CSV Export"
   fun handle(EntityDefinition definition, List<Entity> entities) ---> do the csv export
```

**Comment by Germain-Italic** [comment]
@jmfayard batch select and export look awesome! Hope you can backport this to crudlex!

**Comment by philiplb** [comment]
Closed in favor of https://github.com/philiplb/CRUDlex/issues/70
