### ISSUE TITLE
Serve assets directly using nginx

### ISSUE THREAD

**Issue by dmaciel** [philiplb/CRUDlex#86]
Hi

I'm not sure where to put this, but I notice that the assets where serve trough php, and that is too slow on environments with limited resources (Raspberry Pi). To improve the situation I added the following rule to my nginx host

`
    location /admin/resource/static {
        try_files /vendor/philiplb/crudlex/src/static/$arg_file =404;
    }
`

This will try to serve the assets directly from the filesystem without using php, this improve a lot the performance of the app.

Don't know where to put this in the documentation, so first want to ask the repo maintainer about his thoughts on this

The other idea is to serve the assets directly from a CDN, this will remove the burden for the server and also improve the speed. If you are interested in this route I can create the PR

**Comment by philiplb** [comment]
Good idea. Maybe a chapter "Web Server Optimization" here might do it? https://github.com/philiplb/CRUDlex/blob/master/docs/manual/extendedfeatures.rst
I would investigate something similar for Apache. Should be doable by a rewrite rule.
And then two sub chapters: nginx and Apache.

**Comment by philiplb** [comment]
This is online now in the manual: http://philiplb.github.io/CRUDlex/docs/html/0.12.0/manual/extendedfeatures.html#serving-static-content-via-the-webserver
