### ISSUE TITLE
Abilitiy for additionnal validation constraint

### ISSUE THREAD

**Issue by planeth44** [philiplb/CRUDlex#87]
I don't know if it's better done through .yml definition or to give fieldError control in "before" event.
But at the moment there is no way to validate a field against specific constraint.

**Comment by philiplb** [comment]
Hi, yes, the before moment plus whatever event you want to validate (create, update, ...) is the way to go here: http://philiplb.github.io/CRUDlex/docs/html/0.12.0/manual/events.html
Feel free to reopen if you have any further questions.
