### ISSUE TITLE
Is it possible to chain middleware ?

### ISSUE THREAD

**Issue by planeth44** [philiplb/CRUDlex#88]
As described in Silex documentation, there's a finish middleware that can execute tasks after the Response has been sent to the client.
How could we do it for a particular route? Say for example: /crud/myTable/update/xxx

**Comment by philiplb** [comment]
Hi, sry for the late answer. :)
You can add middlewares to routes after mounting like this:

```PHP
$app->flush();
$route = $app['routes']->get('crudList');
$route->before(function(Symfony\Component\HttpFoundation\Request $request) use ($app) {
    // ...
});
```
Existing routes of CRUDlex are:
- static (I just see, this should be prefixed, I will open another issue for this)
- crudCreate
- crudList
- crudShow
- crudEdit
- crudDelete
- crudRenderFile
- crudDeleteFile
- crudSetLocale

I will also add this to the documentation as it might be usefull. :)
Feel free to reopen if you have any further questions.

**Comment by philiplb** [comment]
(Static route prefix done: https://github.com/philiplb/CRUDlex/commit/889dbad3ab2dea896492a67cbcd59f07049a85b9)

**Comment by philiplb** [comment]
I added some documentation about it: http://philiplb.github.io/CRUDlex/docs/html/0.12.0/manual/routes.html

**Comment by planeth44** [comment]
Thanks a lot
